[project]
authors = [{name = "Seth Warn", email = "swarn@uark.edu"}]
dependencies = []
name = "nitful"
requires-python = ">= 3.12"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project.scripts]
nitful = "nitful.cli:main"

[tool.mypy]
strict = true
python_version = "3.12"
warn_unreachable = true
warn_unused_ignores = true
warn_redundant_casts = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",        # ignore docstrings for now
    "CPY",      # ignore copyright for now
    "DOC201",   # ignore return type in docstrings for now
    "DOC501",   # ignore exceptions in dosctring for now
    "TD",       # ignore TODO checks
    "FIX002",   # "
    "COM812",   # let the formatter handle commas
    "PLW0108",  # ignore lambdas with single call
    "TC001",    # no type-checking block by default
    "TC002",    # "
    "TC003",    # "
    "TC006",    # unquoted types in casts
    "TRY003",   # long exception messages
    "PTH123",   # don't force Path.open()
    "PLC1901",  # explicit empty string checks are OK
    "FBT003",   # allow boolean positional arguments
    "ANN401",   # avoiding Any is difficult while parsing
    "B905",     # allow zip without strict parameter
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "S101",     # assert
    "T201",     # print
    "ANN",      # ignore type annotation
    "PLR2004",  # allow magic values
    "INP001",   # tests aren't a package
]

"**/__init__.py" = [
    "F401",     # unused variables
]

# Let ruff and mypy handle most issues.
[tool.pyright]
reportUnusedImport = "none"
reportUnusedCallResult = "none"
reportExplicitAny = "none"
reportAny = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
