import bisect
import io
from itertools import zip_longest
from pathlib import Path

import pytest

from nitful import ParseError, SerializeError, load, write
from nitful._format.file import read_file, to_fields
from nitful.dsl.rules import Item, ParseContext


def run_strict_roundtrip(filepath: Path) -> None:
    """Check that parsing a file then serializing it again is byte identical."""
    original_bytes = filepath.read_bytes()

    try:
        nitf_file = load(filepath)
    except ParseError as e:
        pytest.fail(f"Parsing failed for {filepath.name}:\n{e}")

    dest_fd = io.BytesIO()

    try:
        write(nitf_file, dest_fd)
    except SerializeError as e:
        pytest.fail(f"Emitting failed for {filepath.name}:\n{e}")

    new_bytes = dest_fd.getvalue()

    if original_bytes == new_bytes:
        return

    # Build a table of field offsets to report the field where the byte
    # difference occurs.
    fields = to_fields(nitf_file)
    field_start_offsets = []
    current_offset = 0
    for f in fields:
        field_start_offsets.append(current_offset)
        current_offset += len(f.value)

    msgs = []
    len_fields = ["FL", "HL", "LISH", "LSSH", "LTSH", "LDSH", "LRESH"]

    for i, (orig, new) in enumerate(zip_longest(original_bytes, new_bytes)):
        if orig != new:
            idx = bisect.bisect_right(field_start_offsets, i) - 1
            valid = 0 <= idx < len(fields)
            field = fields[idx] if valid else Item("UNKNOWN", b"")

            orig_hex = (
                f"0x{orig:02x} ({bytes([orig])!r})"
                if orig is not None
                else "EOF (Missing)"
            )
            new_hex = (
                f"0x{new:02x} ({bytes([new])!r})"
                if new is not None
                else "EOF (Missing)"
            )

            msgs.append(
                f"Byte mismatch at offset {i} (0x{i:04x}) "
                f"inside field {field.name}: {field.value!r}\n"
                f"Expected: {orig_hex}\n"
                f"Got:      {new_hex}"
            )

            # If there's a missing byte, length fields in the header will be
            # different, but just reporting that difference isn't very useful.
            if field.name not in len_fields:
                break

    if len(original_bytes) != len(new_bytes):
        msgs.append(
            f"Length mismatch: Original is {len(original_bytes)} bytes, "
            f"New is {len(new_bytes)} bytes."
        )

    pytest.fail("\n\n".join(msgs))


def run_trace_symmetry(filepath: Path):
    """Ensure field names match between parse and emit.

    When dumping a file, the Field objects generated during parsing are used.
    When dumping a model, the Field objects are generated by to_fields. Verify
    we get the same fields either way, while ignoring the field values, which
    may change to a canonical form.
    """

    with open(filepath, "rb") as fd:
        ctx = ParseContext()
        nitf = read_file(fd, ctx)

    parse_items = [item for (item, _) in ctx.fields]
    emit_items = to_fields(nitf)

    for p_item, e_item in zip_longest(parse_items, emit_items):
        if p_item is None:
            p_str = f"{parse_items[-1].name}: {parse_items[-1].value!r}\n"
            e_str = f"{e_item.name}: {e_item.value!r}\n"
            msg = (
                f"More emitted fields than parsed fields.\n"
                f"  Last parsed field: {p_str}\n"
                f"  Extra emitted field: {e_str}"
            )
            pytest.fail(msg)

        if e_item is None:
            p_str = f"{p_item.name}: {p_item.value!r}\n"
            e_str = f"{emit_items[-1].name}: {emit_items[-1].value!r}\n"
            msg = (
                f"More parsed fields than emitted fields.\n"
                f"  Extra parsed field: {p_str}\n"
                f"  Last emitted field: {e_str}"
            )
            pytest.fail(msg)

        assert p_item.name == e_item.name, (
            f"Different field names for {filepath.name}\n"
            f"  Parse trace expected: {p_item.name}\n"
            f"  Emit trace generated: {e_item.name}"
        )

        assert len(p_item.value) == len(e_item.value), (
            f"Different field sizes for {filepath.name}\n"
            f"  Parse trace for {p_item.name}: {p_item.value!r}\n"
            f"  Emit trace for {e_item.name}: {e_item.value!r}"
        )
