"""Round-trip tests

Verify the parsing and serialization logic by parsing an input file into a
NitfFile object, then serializing the object: a "round trip."
"""

from pathlib import Path

import pytest

from nitful import dump, load

from .helpers import run_strict_roundtrip  # pyrefly: ignore

TEST_DATA_DIR = Path(__file__).parent / "data"


# Files which should round-trip as byte-identical.
STRICT_FILES = list((TEST_DATA_DIR / "strict").glob("*.ntf"))

# Files which may change during round-trip, because the input file is not
# spec-compliant or because the fields can have different representations.
CANONICAL_FILES = list((TEST_DATA_DIR / "canonical").glob("*.ntf"))

ALL_FILES = STRICT_FILES + CANONICAL_FILES


@pytest.mark.parametrize("filepath", STRICT_FILES, ids=lambda p: p.name)
def test_strict_roundtrip(filepath: Path) -> None:
    run_strict_roundtrip(filepath)


@pytest.mark.parametrize("filepath", CANONICAL_FILES, ids=lambda p: p.name)
def test_canonical_roundtrip(filepath: Path):
    golden_path = filepath.with_suffix(".txt")

    nitf = load(filepath)
    actual_text = dump(nitf)

    # If the golden file doesn't exist yet, create it!
    if not golden_path.exists():
        golden_path.write_text(actual_text)
        pytest.fail(f"Created new golden file for {filepath.name}. Verify it manually.")

    expected_text = golden_path.read_text()
    assert actual_text == expected_text


@pytest.mark.parametrize("filepath", ALL_FILES, ids=lambda p: p.name)
def test_trace_symmetry(filepath: Path):
    """Ensure field names match between parse and emit.

    When dumping a file, the Field objects generated during parsing are used.
    When dumping a model, the Field objects are generated by to_fields. Verify
    we get the same fields either way, while ignoring the field values, which
    may change to a canonical form.
    """

    # Dump from a file path to get the parse-time fields.
    parse_dump_text = dump(filepath)

    # Dump from a parsed object to get the emit-time fields.
    nitf = load(filepath)
    emit_dump_text = dump(nitf)

    def extract_names(dump_text: str) -> list[str]:
        names = []
        for line in dump_text.splitlines():
            if line[0].isspace():
                continue
            name = line.split(":", 1)[0]
            names.append(name)
        return names

    parse_names = extract_names(parse_dump_text)
    emit_names = extract_names(emit_dump_text)

    assert len(parse_names) == len(emit_names)

    for i, (p_name, e_name) in enumerate(zip(parse_names, emit_names)):
        assert p_name == e_name, (
            f"Different field names for {filepath.name} at index {i}.\n"
            f"  Parse trace expected: '{p_name}'\n"
            f"  Emit trace generated: '{e_name}'"
        )
